[package]
name = "soa_derive_internal"
version = "0.6.0"
authors = ["Guillaume Fraux <guillaume.fraux@chimie-paristech.fr>"]
license = "MIT/Apache-2.0"
readme = "../README.md"
repository = "https://github.com/lumol-org/soa-derive"
homepage = "https://github.com/lumol-org/soa-derive"
documentation = "https://docs.rs/soa_derive/"
description = """
Internal crate implementation for soa-derive
"""

[lib]
proc-macro = true

[dependencies]
syn = "0.14"
quote = "0.6"
proc-macro2 = "0.4"
